 ## What is Pandas?

To master pandas, you must first understand the two workhorses that power it: the Series and the DataFrame. While NumPy (which we covered in Chapter 4) is great for raw numerical crunching, it lacks a native way to attach labels to data. Pandas solves this by introducing an Index, allowing you to work with data exactly like a spreadsheet or an SQL database.

1. The Series (1D Data)
A Series is a one-dimensional array-like object. Think of it as a single column in an Excel sheet. It contains two main components:

Values: A sequence of data (similar to a NumPy array).

Index: An associated array of data labels.

#### Creating a Basic Series :

When you create a Series without specifying an index, pandas automatically assigns a default integer index starting from 0.

In [ ]:
import pandas as pd 
# Creating a Series from a simple list
obj  = pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64

 #### Customizing the Index:

The real power of a Series emerges when you assign meaningful labels to your data points. This allows you to select data by its label instead of its numerical position.

In [ ]:
# Creating a Series with a custom index:
sales = pd.Series([400, 700, 500, 300] , index = ['Jan' , 'Feb' , 'Mar', 'Apr'])
print(sales)

# Selecting data using the label:
print(sales['Feb'])   # Output: 700

Jan    400
Feb    700
Mar    500
Apr    300
dtype: int64
700

#### Series as a Dictionary: 

Because a Series maps an index label to a value, you can actually think of it as a fixed-length, ordered Python dictionary. In fact, you can create a Series directly from a dictionary!

In [11]:
Marks = {'Yashraj' : 40 , 'Annu' : 90 , 'Aman' : 70} 
Marks_series =  pd.Series(Marks)
print(Marks_series)

Yashraj    40
Annu       90
Aman       70
dtype: int64

 #### 2. The DataFrame (2D Tabular Data): 
A DataFrame is a two-dimensional, rectangular table of data. Think of it as an entire Excel spreadsheet. It contains an ordered collection of columns, where each column can be a different value type (numeric, string, boolean, etc.).

Under the hood, a DataFrame is essentially a dictionary of Series objects that all share the same index.

Creating a DataFrame

The most common way to create a DataFrame from scratch is using a dictionary of equal-length lists or NumPy arrays.

In [23]:
data = {
    'state' : ['Rajasthan' , 'Rajasthan' , 'Haryana' , 'Kerela' , 'Madhya_Pradesh'],
    'year' : [ 2000 , 2001 , 2002 , 2003 , 2004 ],
    'name' : ['Yashraj' , 'Rahul' , 'Sahil' , 'Utkarsh' , 'halwa']
}

df = pd.DataFrame(data)
print(df)

            state  year     name
0       Rajasthan  2000  Yashraj
1       Rajasthan  2001    Rahul
2         Haryana  2002    Sahil
3          Kerela  2003  Utkarsh
4  Madhya_Pradesh  2004    halwa

Key DataFrame Methods :

df.head(): Returns the first 5 rows (invaluable for large datasets).

Selecting a Column: You can extract a single column as a Series using dictionary-like notation (df['state']) or attribute notation (df.state).

In [15]:
df.head()

           state   year     name
0       Rajasthan  2000  Yashraj
1       Rajasthan  2001    Rahul
2         Haryana  2002    Sahil
3          Kerela  2003  Utkarsh
4  Madhya_Pradesh  2004    halwa

In [26]:
print(df['state'])
df.state

0         Rajasthan
1         Rajasthan
2           Haryana
3            Kerela
4    Madhya_Pradesh
Name: state, dtype: object

0         Rajasthan
1         Rajasthan
2           Haryana
3            Kerela
4    Madhya_Pradesh
Name: state, dtype: object

### 3. Index Objects

Both Series and DataFrames utilize Index objects to hold axis labels (and other metadata like axis names).

The most critical rule regarding pandas Index objects is that they are immutable (they cannot be modified by the user once created).

In [31]:
my_index = pd.Index(['a','b','c'])
# my_index[1] = 'd'    <-- THIS WILL THROW A TYPE ERROR!

Why Immutability Matters: Because indexes cannot be changed, it is completely safe to share them between different DataFrames and Series without worrying about accidental modifications corrupting your data structure.

## Lecture 2 -> Essential Functionality (Manipulation & Selection).

Now that you know how to build a Series and a DataFrame, you need to know how to surgically extract the exact data you want, or get rid of the data you don't. This is where pandas truly shines.

#### 1. Dropping Entries (Cleaning House)
Often, you'll have rows or columns you simply don't need. The drop method returns a new object with the specified values removed from an axis.

In [39]:
# Let's create a quick Series
import numpy as np 
obj = pd.Series(np.arange(5.) , index = ['a' , 'b' , 'c' , 'd' , 'e'])
print(obj)

# Drop rows 'c' and 'd'
new_obj = obj.drop(['c' , 'd'])
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
e    4.0
dtype: float64

Dropping Columns (using axis=1):

When working with a DataFrame, if you want to drop a column instead of a row, you must explicitly tell pandas to look at the columns by passing axis=1 (or axis='columns').

### Examples :

In [43]:
df = pd.DataFrame(
    np.arange(20).reshape(5,4),
    index = ['a', 'b' ,'c' , 'd' ,'e'],
    columns = ['one', 'two' ,'three' ,'four']

)
print(df)

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
e   16   17     18    19

In [ ]:
# Drop One Column:
new_df = df.drop('two' , axis = 1)  #axis=1 → columns (across)
print(new_df)

   one  three  four
a    0      2     3
b    4      6     7
c    8     10    11
d   12     14    15
e   16     18    19

In [49]:
# Drop Multiple Columns
new_df = df.drop(['two' ,'three'] , axis = 1)
print(new_df)

   one  four
a    0     3
b    4     7
c    8    11
d   12    15
e   16    19

In [52]:
# Using columns= Instead of axis=1
new_df = df.drop(columns = ['two' ,'three'])
print(new_df)

   one  four
a    0     3
b    4     7
c    8    11
d   12    15
e   16    19

In [54]:
#Using index= for Rows
new_df = df.drop(index = ['a', 'd'])
print(new_df)

   one  two  three  four
b    4    5      6     7
c    8    9     10    11
e   16   17     18    19

 #### 2. The Golden Rule of Selection: .loc vs .iloc
If there is one thing you memorize from Chapter 5, make it this. Selecting data in pandas can be confusing because you can select by a label (like 'Ohio') or by an integer position (like row 0).

Pandas created two specific operators to make this crystal clear:

.loc (Label-based): You ask for data based on the names of the index or columns.

.iloc (Integer-based): You ask for data based on its numerical position (starting from 0), exactly like standard Python lists.

In [62]:
data = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                    index=['Ohio', 'Colorado', 'Utah'], 
                    columns=['one', 'two', 'three'])

print(data)

# 1. Grab Colorado's data using its label (.loc):
print(data.loc['Colorado'])

# 2. Grab Colorado's data using its row number (.iloc):
print(data.iloc[1])

# 3. Grab a specific slice (Rows Colorado & Utah, Columns 'two' & 'three')
print(data.loc['Colorado':'Utah' , 'two':'three'])

          one  two  three
Ohio        0    1      2
Colorado    3    4      5
Utah        6    7      8
one      3
two      4
three    5
Name: Colorado, dtype: int64
one      3
two      4
three    5
Name: Colorado, dtype: int64
          two  three
Colorado    4      5
Utah        7      8

Important Note:

 When slicing with .loc (labels), the endpoint is inclusive (it includes 'Utah'). When slicing with .iloc (integers) or standard Python, the endpoint is exclusive.

###  3. Filtering (Boolean Indexing)
You will rarely just say "give me row 5". Instead, you'll ask questions like "give me all rows where the value in column 'three' is greater than 5". You do this by passing a condition directly into the brackets.

In [ ]:
filtered_data = data[data['three']>=5]
print(filtered_data)      # exmaple of single condition

          one  two  three
Colorado    3    4      5
Utah        6    7      8

### Example:

In [67]:
import pandas as pd

data = pd.DataFrame({
    'one':   [1, 2, 3, 4, 5],
    'two':   [10, 20, 30, 40, 50],
    'three': [2, 7, 4, 9, 6]
})

print(data)

   one  two  three
0    1   10      2
1    2   20      7
2    3   30      4
3    4   40      9
4    5   50      6

In [68]:
# Equal To:
data[data['one']==3]

   one  two  three
2    3   30      4

In [69]:
# Not Equal To:
data[data['three'] !=4]

   one  two  three
0    1   10      2
1    2   20      7
3    4   40      9
4    5   50      6

In [70]:
# Multiple Conditions (AND):
data[(data['three']>5)  & (data['two']>30)]

   one  two  three
3    4   40      9
4    5   50      6

In [71]:
# 8. Filter Specific Columns After Filtering:
# Rows where three > 5, but show only one and three.
data.loc[data['three'] > 5, ['one', 'three']]

   one  three
1    2      7
3    4      9
4    5      6

In [72]:
#Using .isin()
#Find rows where one is either 1, 3, or 5.
data[data['one'].isin([1, 3, 5])]

   one  two  three
0    1   10      2
2    3   30      4
4    5   50      6

In [73]:
# String Filtering

df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 28]
})
df[df['name'] == 'Alice']

    name  age
0  Alice   25

In [75]:
# String Contains
df[df['name'].str.contains('a', case=False)]

      name  age
0    Alice   25
2  Charlie   35
3    David   28