 ## What is Pandas?

To master pandas, you must first understand the two workhorses that power it: the Series and the DataFrame. While NumPy (which we covered in Chapter 4) is great for raw numerical crunching, it lacks a native way to attach labels to data. Pandas solves this by introducing an Index, allowing you to work with data exactly like a spreadsheet or an SQL database.

1. The Series (1D Data)
A Series is a one-dimensional array-like object. Think of it as a single column in an Excel sheet. It contains two main components:

Values: A sequence of data (similar to a NumPy array).

Index: An associated array of data labels.

#### Creating a Basic Series :

When you create a Series without specifying an index, pandas automatically assigns a default integer index starting from 0.

In [ ]:
import pandas as pd 
# Creating a Series from a simple list
obj  = pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64

 #### Customizing the Index:

The real power of a Series emerges when you assign meaningful labels to your data points. This allows you to select data by its label instead of its numerical position.

In [ ]:
# Creating a Series with a custom index:
sales = pd.Series([400, 700, 500, 300] , index = ['Jan' , 'Feb' , 'Mar', 'Apr'])
print(sales)

# Selecting data using the label:
print(sales['Feb'])   # Output: 700

Jan    400
Feb    700
Mar    500
Apr    300
dtype: int64
700

#### Series as a Dictionary: 

Because a Series maps an index label to a value, you can actually think of it as a fixed-length, ordered Python dictionary. In fact, you can create a Series directly from a dictionary!

In [11]:
Marks = {'Yashraj' : 40 , 'Annu' : 90 , 'Aman' : 70} 
Marks_series =  pd.Series(Marks)
print(Marks_series)

Yashraj    40
Annu       90
Aman       70
dtype: int64

 #### 2. The DataFrame (2D Tabular Data): 
A DataFrame is a two-dimensional, rectangular table of data. Think of it as an entire Excel spreadsheet. It contains an ordered collection of columns, where each column can be a different value type (numeric, string, boolean, etc.).

Under the hood, a DataFrame is essentially a dictionary of Series objects that all share the same index.

Creating a DataFrame

The most common way to create a DataFrame from scratch is using a dictionary of equal-length lists or NumPy arrays.

In [23]:
data = {
    'state' : ['Rajasthan' , 'Rajasthan' , 'Haryana' , 'Kerela' , 'Madhya_Pradesh'],
    'year' : [ 2000 , 2001 , 2002 , 2003 , 2004 ],
    'name' : ['Yashraj' , 'Rahul' , 'Sahil' , 'Utkarsh' , 'halwa']
}

df = pd.DataFrame(data)
print(df)

            state  year     name
0       Rajasthan  2000  Yashraj
1       Rajasthan  2001    Rahul
2         Haryana  2002    Sahil
3          Kerela  2003  Utkarsh
4  Madhya_Pradesh  2004    halwa

Key DataFrame Methods :

df.head(): Returns the first 5 rows (invaluable for large datasets).

Selecting a Column: You can extract a single column as a Series using dictionary-like notation (df['state']) or attribute notation (df.state).

In [15]:
df.head()

           state   year     name
0       Rajasthan  2000  Yashraj
1       Rajasthan  2001    Rahul
2         Haryana  2002    Sahil
3          Kerela  2003  Utkarsh
4  Madhya_Pradesh  2004    halwa

In [26]:
print(df['state'])
df.state

0         Rajasthan
1         Rajasthan
2           Haryana
3            Kerela
4    Madhya_Pradesh
Name: state, dtype: object

0         Rajasthan
1         Rajasthan
2           Haryana
3            Kerela
4    Madhya_Pradesh
Name: state, dtype: object

### 3. Index Objects

Both Series and DataFrames utilize Index objects to hold axis labels (and other metadata like axis names).

The most critical rule regarding pandas Index objects is that they are immutable (they cannot be modified by the user once created).

In [31]:
my_index = pd.Index(['a','b','c'])
# my_index[1] = 'd'    <-- THIS WILL THROW A TYPE ERROR!

Why Immutability Matters: Because indexes cannot be changed, it is completely safe to share them between different DataFrames and Series without worrying about accidental modifications corrupting your data structure.

## Lecture 2 -> Essential Functionality (Manipulation & Selection).

Now that you know how to build a Series and a DataFrame, you need to know how to surgically extract the exact data you want, or get rid of the data you don't. This is where pandas truly shines.

#### 1. Dropping Entries (Cleaning House)
Often, you'll have rows or columns you simply don't need. The drop method returns a new object with the specified values removed from an axis.

In [39]:
# Let's create a quick Series
import numpy as np 
obj = pd.Series(np.arange(5.) , index = ['a' , 'b' , 'c' , 'd' , 'e'])
print(obj)

# Drop rows 'c' and 'd'
new_obj = obj.drop(['c' , 'd'])
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
e    4.0
dtype: float64

Dropping Columns (using axis=1):

When working with a DataFrame, if you want to drop a column instead of a row, you must explicitly tell pandas to look at the columns by passing axis=1 (or axis='columns').

### Examples :

In [43]:
df = pd.DataFrame(
    np.arange(20).reshape(5,4),
    index = ['a', 'b' ,'c' , 'd' ,'e'],
    columns = ['one', 'two' ,'three' ,'four']

)
print(df)

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
e   16   17     18    19

In [ ]:
# Drop One Column:
new_df = df.drop('two' , axis = 1)  #axis=1 → columns (across)
print(new_df)

   one  three  four
a    0      2     3
b    4      6     7
c    8     10    11
d   12     14    15
e   16     18    19

In [49]:
# Drop Multiple Columns
new_df = df.drop(['two' ,'three'] , axis = 1)
print(new_df)

   one  four
a    0     3
b    4     7
c    8    11
d   12    15
e   16    19

In [52]:
# Using columns= Instead of axis=1
new_df = df.drop(columns = ['two' ,'three'])
print(new_df)

   one  four
a    0     3
b    4     7
c    8    11
d   12    15
e   16    19

In [54]:
#Using index= for Rows
new_df = df.drop(index = ['a', 'd'])
print(new_df)

   one  two  three  four
b    4    5      6     7
c    8    9     10    11
e   16   17     18    19

 #### 2. The Golden Rule of Selection: .loc vs .iloc
If there is one thing you memorize from Chapter 5, make it this. Selecting data in pandas can be confusing because you can select by a label (like 'Ohio') or by an integer position (like row 0).

Pandas created two specific operators to make this crystal clear:

.loc (Label-based): You ask for data based on the names of the index or columns.

.iloc (Integer-based): You ask for data based on its numerical position (starting from 0), exactly like standard Python lists.

In [62]:
data = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                    index=['Ohio', 'Colorado', 'Utah'], 
                    columns=['one', 'two', 'three'])

print(data)

# 1. Grab Colorado's data using its label (.loc):
print(data.loc['Colorado'])

# 2. Grab Colorado's data using its row number (.iloc):
print(data.iloc[1])

# 3. Grab a specific slice (Rows Colorado & Utah, Columns 'two' & 'three')
print(data.loc['Colorado':'Utah' , 'two':'three'])

          one  two  three
Ohio        0    1      2
Colorado    3    4      5
Utah        6    7      8
one      3
two      4
three    5
Name: Colorado, dtype: int64
one      3
two      4
three    5
Name: Colorado, dtype: int64
          two  three
Colorado    4      5
Utah        7      8

Important Note:

 When slicing with .loc (labels), the endpoint is inclusive (it includes 'Utah'). When slicing with .iloc (integers) or standard Python, the endpoint is exclusive.

###  3. Filtering (Boolean Indexing)
You will rarely just say "give me row 5". Instead, you'll ask questions like "give me all rows where the value in column 'three' is greater than 5". You do this by passing a condition directly into the brackets.

In [ ]:
filtered_data = data[data['three']>=5]
print(filtered_data)      # exmaple of single condition

          one  two  three
Colorado    3    4      5
Utah        6    7      8

### Example:

In [67]:
import pandas as pd

data = pd.DataFrame({
    'one':   [1, 2, 3, 4, 5],
    'two':   [10, 20, 30, 40, 50],
    'three': [2, 7, 4, 9, 6]
})

print(data)

   one  two  three
0    1   10      2
1    2   20      7
2    3   30      4
3    4   40      9
4    5   50      6

In [68]:
# Equal To:
data[data['one']==3]

   one  two  three
2    3   30      4

In [69]:
# Not Equal To:
data[data['three'] !=4]

   one  two  three
0    1   10      2
1    2   20      7
3    4   40      9
4    5   50      6

In [70]:
# Multiple Conditions (AND):
data[(data['three']>5)  & (data['two']>30)]

   one  two  three
3    4   40      9
4    5   50      6

In [71]:
# 8. Filter Specific Columns After Filtering:
# Rows where three > 5, but show only one and three.
data.loc[data['three'] > 5, ['one', 'three']]

   one  three
1    2      7
3    4      9
4    5      6

In [72]:
#Using .isin()
#Find rows where one is either 1, 3, or 5.
data[data['one'].isin([1, 3, 5])]

   one  two  three
0    1   10      2
2    3   30      4
4    5   50      6

In [73]:
# String Filtering

df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 28]
})
df[df['name'] == 'Alice']

    name  age
0  Alice   25

In [75]:
# String Contains
df[df['name'].str.contains('a', case=False)]

      name  age
0    Alice   25
2  Charlie   35
3    David   28

## Lecture 3: Essential Functionality (Operations).

Now that you know how to build, slice, and filter DataFrames, it is time to make them do some actual work. In this lecture, we will cover how pandas handles math between mismatched datasets, how to apply your own custom functions, and how to get your data organized.

#### 1. Arithmetic and Data Alignment:
One of the most powerful (and sometimes surprising) features of pandas is how it handles arithmetic between objects with different indexes.

If you add two Series or DataFrames together, pandas does not just blindly add row 1 to row 1. It looks at the index labels and aligns the data first. If a label exists in one dataset but not the other, pandas introduces a NaN (Not a Number), which represents missing data.

In [79]:
s1 = pd.Series([7.3,-2.5,3.4,1.5] , index = ['a','b','c','d'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

# Adding them together:
result = s1 + s2
print(result)

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

Notice how d, f, and g became NaN. They didn't have a partner to add with, and in pandas, any math operation involving a NaN results in another NaN.

The Solution: Using Arithmetic Methods with Fill Values:

To prevent missing data from ruining your calculations, use the built-in arithmetic methods (.add(), .sub(), .div(), .mul()) and pass a fill_value.

### Examples:

In [81]:
# Using fill_value:
result = s1.add(s2 ,fill_value =0 )
print(result)

a    5.2
b   -2.5
c    7.0
d    1.5
e   -1.5
f    4.0
g    3.1
dtype: float64

In [84]:
# Subtraction Between Series:
s1 = pd.Series([100, 200, 300], index=['A', 'B', 'C'])
s2 = pd.Series([50, 75, 25], index=['B', 'C', 'D'])
print(s1 - s2)
result = s1.sub(s2 , fill_value = 0)
print(result)

A      NaN
B    150.0
C    225.0
D      NaN
dtype: float64
A    100.0
B    150.0
C    225.0
D    -25.0
dtype: float64

In [89]:
# DataFrame Addition:
df1 = pd.DataFrame(
    [[1, 2], [3, 4]],
    index=['row1', 'row2'],
    columns=['A', 'B']
)
print(df1)

df2 = pd.DataFrame(
    [[10, 20], [30, 40]],
    index=['row2', 'row3'],
    columns=['B', 'C']
)
print(df2)

print(df1 + df2)

      A  B
row1  1  2
row2  3  4
       B   C
row2  10  20
row3  30  40
       A     B   C
row1 NaN   NaN NaN
row2 NaN  14.0 NaN
row3 NaN   NaN NaN

In [93]:
 # DataFrame with fill_value:
result = df1.add(df2 , fill_value = 0)
print(result)

        A     B     C
row1  1.0   2.0   NaN
row2  3.0  14.0  20.0
row3  NaN  30.0  40.0

In [94]:
# Multiplication:
s1 = pd.Series([2, 4, 6], index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30], index=['b', 'c', 'd'])

print(s1 * s2)
print(s1/s2)

a      NaN
b     40.0
c    120.0
d      NaN
dtype: float64
a    NaN
b    0.4
c    0.3
d    NaN
dtype: float64

#### 2. Function Application and Mapping:

NumPy functions (like np.abs() to get absolute values) work perfectly fine on pandas objects. However, you will often want to apply your own custom functions to your data.

Using .apply() on DataFrames:

The .apply() method allows you to run a function on an entire row or column at once. It is incredibly common to use Python lambda (anonymous) functions here for quick calculations.

In [98]:
df = pd.DataFrame(
    np.random.randn(4,3),
    columns=['A', 'B', 'C'], 
    index=['Utah', 'Ohio', 'Texas', 'Oregon']

)
print(df )
## Calculate the range (max minus min) for each COLUMN:
range_func = lambda x: x.max() - x.min()
df.apply(range_func)

               A         B         C
Utah    0.831834  0.154047 -0.192303
Ohio   -1.161352  1.349275  1.558187
Texas  -0.547242 -2.303335  0.075203
Oregon -1.434804  2.110128 -0.623763

A    2.266638
B    4.413463
C    2.181949
dtype: float64

Using .map() on a Series:

If you want to transform every single individual element in a Series, you use .map(). This is highly useful for cleaning text or mapping dictionary values.

In [101]:
# Mapping a formatting function to every element in a Series:
format_func = lambda x: f"{x:.2f}"
formatted_series = df['A'].map(format_func)
print(formatted_series)

Utah       0.83
Ohio      -1.16
Texas     -0.55
Oregon    -1.43
Name: A, dtype: object

#### 3. Sorting and Ranking:

Sorting datasets by an essential criterion is a daily task in data analysis. Pandas gives you two main ways to sort: by the index labels, or by the actual data values.

Sorting by Index (.sort_index())

This returns a new, sorted object based on the row or column labels.

In [104]:
unsorted_df = pd.DataFrame(np.arange(4).reshape((2, 2)), 
                           index=['three', 'one'], 
                           columns=['d', 'a'])
print(unsorted_df)
# Sort rows alphabetically by their index labels :
print(unsorted_df.sort_index())

       d  a
three  0  1
one    2  3
       d  a
one    2  3
three  0  1

| Method                             | What it sorts                  |
| ---------------------------------- | ------------------------------ |
| `df.sort_index()`                  | Row labels (index)             |
| `df.sort_index(axis=1)`            | Column labels                  |
| `df.sort_index(ascending=False)`   | Reverse order                  |
| `df.sort_values(by='column_name')` | Actual data values in a column |

In [106]:
print(unsorted_df.sort_index(axis=1))
print(unsorted_df.sort_index(ascending =False))

       a  d
three  1  0
one    3  2
       d  a
three  0  1
one    2  3

Sorting by Values (.sort_values()):

This is the one you will use most often. You can sort a DataFrame by the data in one or more specific columns

In [112]:
data = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(data)
sorted_data = data.sort_values(by = "b")
print(sorted_data['b'])

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
2   -3
3    2
0    4
1    7
Name: b, dtype: int64

Pro-tip: If you want to sort from highest to lowest, simply add ascending=False inside the parentheses: data.sort_values(by='b', ascending=False).

In [113]:
data.sort_values(by='b', ascending=False)

   b  a
1  7  1
0  4  0
3  2  1
2 -3  0

##  Lecture 4: Descriptive Statistics & Data Exploration.

This is the final lecture for Chapter 5. Now that you know how to build, slice, and manipulate your DataFrames, it is time to actually analyze them. Pandas comes equipped with a massive toolkit of mathematical and statistical methods designed to summarize your data quickly.

#### 1. Summarizing and Computing Statistics:

Pandas has built-in methods to extract single values (like the sum or mean) from an entire row or column. By default, these methods operate over columns (down the rows).

Basic Math (.sum(), .mean())

A fantastic feature of pandas is that it automatically excludes missing data (NaN) when calculating these statistics, unlike raw NumPy which would return NaN.

In [116]:
df = pd.DataFrame([[1.4 , np.nan] , [7.1 , -4.5] , [np.nan , np.nan] ,[0.75, -1.3]],
                  index= ['a', 'b', 'c', 'd'],
                  columns = ['one' , 'two'])

print(df)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [127]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [130]:
print(df.mean(axis = 'index'))

one    3.083333
two   -2.900000
dtype: float64

The Magic Method: .describe()
When you first load a dataset, you want a bird's-eye view of your data. The .describe() method computes multiple summary statistics simultaneously.

For numeric data, this will instantly give you the count, mean, standard deviation, minimum, maximum, and the 25%, 50% (median), and 75% quartiles!

In [129]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

2. Correlation and Covariance

In data analysis, you often want to know if two columns are related. For example, if advertising spend goes up, do sales go up too?

Correlation (.corr()): Measures how closely two variables move together on a scale of -1 to 1.

Covariance (.cov()): Measures the directional relationship between the variables (unscaled).

### Example:

In [131]:
import pandas as pd

df = pd.DataFrame({
    'Advertising': [10, 20, 30, 40, 50],
    'Sales': [100, 120, 140, 160, 180]
})

print(df)

   Advertising  Sales
0           10    100
1           20    120
2           30    140
3           40    160
4           50    180

In [132]:
#Correlation (corr()):
print(df['Advertising'].corr(df['Sales']))

1.0

In [133]:
# Negative Correlation:
df = pd.DataFrame({
    'Exercise_Hours': [1, 2, 3, 4, 5],
    'Body_Fat': [30, 25, 20, 15, 10]
})

print(df['Exercise_Hours'].corr(df['Body_Fat']))

-1.0

In [135]:
#Covariance (cov())
# Covariance tells us whether variables move together.
df = pd.DataFrame({
    'Advertising': [10, 20, 30, 40, 50],
    'Sales': [100, 120, 140, 160, 180]
})
print(df['Advertising'].cov(df['Sales']))

500.0

| Feature           | Correlation (`corr`) | Covariance (`cov`) |
| ----------------- | -------------------- | ------------------ |
| Range             | -1 to 1              | No fixed range     |
| Shows Direction   | Yes                  | Yes                |
| Shows Strength    | Yes                  | Not directly       |
| Affected by Units | No                   | Yes                |
| Commonly Used     | Very often           | Less often         |

#### 3. Unique Values, Value Counts, and Membership

These tools are essential for exploring 1D data (Series) and understanding categorical variables (like "State", "Color", or "Status").

Finding Unique Values (.unique())

Gives you an array of all the distinct values in a column.

In [137]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

Counting Frequencies (.value_counts())

This is arguably one of the most frequently used functions in pandas. It tells you exactly how many times each unique value appears, automatically sorted in descending order.

In [138]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

Filtering with .isin()

If you want to filter a massive dataset down to just a few specific categories, .isin() creates a boolean mask you can use for selection.

In [142]:
mask = obj.isin(['b' ,'c'])
print(mask)
# Keep only the rows where the value is either 'b' or 'c
obj[mask]

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

0    c
5    b
6    b
7    c
8    c
dtype: object